//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CumputerComponentsUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CumputerComponentsUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, start choose components.
        /// </summary>
        internal static string ChooseComponents {
            get {
                return ResourceManager.GetString("ChooseComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select CPU and Motherboard with the same socket.
        /// </summary>
        internal static string CPUAndMotherboardProblems {
            get {
                return ResourceManager.GetString("CPUAndMotherboardProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose Fan with the same socket as CPU.
        /// </summary>
        internal static string FansSocketNotCompatibility {
            get {
                return ResourceManager.GetString("FansSocketNotCompatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will be better if you choose Fan with bigger TDP then CPUs.
        /// </summary>
        internal static string FansTDPSmallerThenCPUs {
            get {
                return ResourceManager.GetString("FansTDPSmallerThenCPUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All components will work fine.
        /// </summary>
        internal static string ItsFineAssembly {
            get {
                return ResourceManager.GetString("ItsFineAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, choose all important components (*).
        /// </summary>
        internal static string NotAllImportantComponents {
            get {
                return ResourceManager.GetString("NotAllImportantComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, choose Power Supply with more power.
        /// </summary>
        internal static string NotEnoughPowerOfPS {
            get {
                return ResourceManager.GetString("NotEnoughPowerOfPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, choose CPU with graphical core OR select GPU.
        /// </summary>
        internal static string ThereAreNotGraphicalCores {
            get {
                return ResourceManager.GetString("ThereAreNotGraphicalCores", resourceCulture);
            }
        }
    }
}
